/* tslint:disable */
/* eslint-disable */
/**
 * Financial System API
 * API для керування банківськими рахунками та транзакціями.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AccountInput {
    'owner_name'?: string;
    'currency'?: string;
}
export interface TransactionInput {
    'from_account_id'?: string;
    'to_account_id'?: string;
    'amount'?: number;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Отримати список рахунків
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/accounts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Створити рахунок
         * @param {AccountInput} accountInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountsPost: async (accountInput: AccountInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountInput' is not null or undefined
            assertParamExists('accountsPost', 'accountInput', accountInput)
            const localVarPath = `/accounts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(accountInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Виконати транзакцію
         * @param {TransactionInput} transactionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsPost: async (transactionInput: TransactionInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'transactionInput' is not null or undefined
            assertParamExists('transactionsPost', 'transactionInput', transactionInput)
            const localVarPath = `/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(transactionInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Отримати список рахунків
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.accountsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Створити рахунок
         * @param {AccountInput} accountInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountsPost(accountInput: AccountInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountsPost(accountInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.accountsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Виконати транзакцію
         * @param {TransactionInput} transactionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionsPost(transactionInput: TransactionInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionsPost(transactionInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.transactionsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Отримати список рахунків
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountsGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Створити рахунок
         * @param {AccountInput} accountInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountsPost(accountInput: AccountInput, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountsPost(accountInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Виконати транзакцію
         * @param {TransactionInput} transactionInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionsPost(transactionInput: TransactionInput, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.transactionsPost(transactionInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Отримати список рахунків
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).accountsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Створити рахунок
     * @param {AccountInput} accountInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountsPost(accountInput: AccountInput, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).accountsPost(accountInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Виконати транзакцію
     * @param {TransactionInput} transactionInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public transactionsPost(transactionInput: TransactionInput, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).transactionsPost(transactionInput, options).then((request) => request(this.axios, this.basePath));
    }
}



